version: "3.8"

services:
  postgres:
    image: postgres:12
    container_name: ngi_secoge_postgres
    environment:
      POSTGRES_USER: ngisecoge
      POSTGRES_PASSWORD: ngisecoge
      POSTGRES_DB: ngisecoge
    volumes:
      - ./data:/docker-entrypoint-initdb.d  # Mapeia o diretório 'data' para o diretório de inicialização do PostgreSQL
    command: bash -c "chown -R postgres:postgres /docker-entrypoint-initdb.d/ && chmod 644 /docker-entrypoint-initdb.d/transformado_INFLUD24-20-01-2025.csv && docker-entrypoint.sh postgres"
    ports:
      - "5432:5432"
    networks:
      - ngi_secoge_net

  airflow:
    image: apache/airflow:2.5.0
    container_name: ngi_secoge_airflow
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://ngisecoge:ngisecoge@postgres:5432/ngisecoge  # Corrigido para usar o banco correto
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - ngi_secoge_net

networks:
  ngi_secoge_net:
    driver: bridge
